"""Opening a database an older build wrote.

A hub in a container was upgraded from the build tagged here as *before subjects*
to the one after `retracted_at` landed, and went into a restart loop:
`sqlite3.OperationalError: no such column: supersedes`. It was recovered by wiping
the volume, which for a store that is the only copy of the sediment on it means
the upgrade destroyed the product. Nothing in the suite went red, before or after.

**The reason nothing went red is the reason this file exists.** The upgrade test
that already existed built its "old" database by calling `SqliteStore(path)` and
then dropping one table — so `notes` was left entirely modern and the index that
crashes could still be built. A fixture generated by the code under test can only
ever represent the schema the code under test writes, which is precisely the one
thing an upgrade test must not assume. That test is still in `test_subjects.py`
and its docstring now says which half it covers.

So the schemas below are **literal SQL, copied verbatim from `git show
<sha>:src/cairn/store.py`**, and they are checked in as a record of what those
builds actually wrote rather than as a description of what they meant to. They do
not get updated when `store.py` changes; a new one gets added underneath. The
oldest was validated against the real pre-upgrade database off the container hub,
which reproduces the same failure and is not committed — it is a production store
full of real hostnames, and its schema was what was wanted, not its bytes.
"""

from __future__ import annotations

import json
import sqlite3

import pytest

from cairn.store import _INDEXES, _TABLES, BACKFILLED_AUTHOR, SqliteStore
from cairn.wire import Agent

SCRIBE = "bench/firmware"
PEER = "rig-a/hil"

# Verbatim from `git show 7af6ba3:src/cairn/store.py`. No `subjects` table, and a
# six-column `notes`: no `supersedes`, no `deleted_at`, no `deleted_by`. This is
# the shape the container hub was actually running: one table and four columns behind,
# across three releases. Unchanged from the first published build up to this one.
_BEFORE_SUBJECTS = """
CREATE TABLE IF NOT EXISTS agents (
    name          TEXT PRIMARY KEY,
    machine       TEXT NOT NULL,
    cwd           TEXT NOT NULL,
    capabilities  TEXT NOT NULL,
    session_id    TEXT,
    registered_at TEXT NOT NULL,
    last_seen     TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
    seq            INTEGER PRIMARY KEY AUTOINCREMENT,
    kind           TEXT NOT NULL,
    sender         TEXT NOT NULL,
    recipient      TEXT NOT NULL,
    body           TEXT NOT NULL,
    correlation_id TEXT,
    artifacts      TEXT NOT NULL,
    created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS messages_by_recipient ON messages (recipient, seq);
CREATE INDEX IF NOT EXISTS messages_by_sender ON messages (sender, seq);
CREATE TABLE IF NOT EXISTS cursors (
    agent          TEXT PRIMARY KEY,
    last_acked_seq INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS notes (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    subject    TEXT NOT NULL,
    author     TEXT NOT NULL,
    body       TEXT NOT NULL,
    question   INTEGER NOT NULL DEFAULT 0,
    settles    INTEGER REFERENCES notes (id),
    artifacts  TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS notes_by_subject ON notes (subject, id);
CREATE INDEX IF NOT EXISTS notes_by_settles ON notes (settles);
"""

# Verbatim from `git show 41a86cb:src/cairn/store.py`. `subjects` has arrived as a
# whole new table, which `CREATE TABLE IF NOT EXISTS` carries to an existing
# database on its own — this is the last shape that upgraded in place without
# anybody noticing there was a mechanism.
_BEFORE_SUPERSEDES = """
CREATE TABLE IF NOT EXISTS agents (
    name          TEXT PRIMARY KEY,
    machine       TEXT NOT NULL,
    cwd           TEXT NOT NULL,
    capabilities  TEXT NOT NULL,
    session_id    TEXT,
    registered_at TEXT NOT NULL,
    last_seen     TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
    seq            INTEGER PRIMARY KEY AUTOINCREMENT,
    kind           TEXT NOT NULL,
    sender         TEXT NOT NULL,
    recipient      TEXT NOT NULL,
    body           TEXT NOT NULL,
    correlation_id TEXT,
    artifacts      TEXT NOT NULL,
    created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS messages_by_recipient ON messages (recipient, seq);
CREATE INDEX IF NOT EXISTS messages_by_sender ON messages (sender, seq);
CREATE TABLE IF NOT EXISTS cursors (
    agent          TEXT PRIMARY KEY,
    last_acked_seq INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS notes (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    subject    TEXT NOT NULL,
    author     TEXT NOT NULL,
    body       TEXT NOT NULL,
    question   INTEGER NOT NULL DEFAULT 0,
    settles    INTEGER REFERENCES notes (id),
    artifacts  TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS notes_by_subject ON notes (subject, id);
CREATE INDEX IF NOT EXISTS notes_by_settles ON notes (settles);
CREATE TABLE IF NOT EXISTS subjects (
    name        TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    created_by  TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    archived_at TEXT,
    archived_by TEXT
);
"""

# Verbatim from `git show 241d207:src/cairn/store.py` — the build that introduced
# both `_MIGRATIONS` and the defect, by putting `notes_by_supersedes` in the same
# script as the `CREATE TABLE` that is a no-op on an existing database. A store
# *written* by this build is fine; every store written before it was not.
_BEFORE_RETRACTION = """
CREATE TABLE IF NOT EXISTS agents (
    name          TEXT PRIMARY KEY,
    machine       TEXT NOT NULL,
    cwd           TEXT NOT NULL,
    capabilities  TEXT NOT NULL,
    session_id    TEXT,
    registered_at TEXT NOT NULL,
    last_seen     TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
    seq            INTEGER PRIMARY KEY AUTOINCREMENT,
    kind           TEXT NOT NULL,
    sender         TEXT NOT NULL,
    recipient      TEXT NOT NULL,
    body           TEXT NOT NULL,
    correlation_id TEXT,
    artifacts      TEXT NOT NULL,
    created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS messages_by_recipient ON messages (recipient, seq);
CREATE INDEX IF NOT EXISTS messages_by_sender ON messages (sender, seq);
CREATE TABLE IF NOT EXISTS cursors (
    agent          TEXT PRIMARY KEY,
    last_acked_seq INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS notes (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    subject    TEXT NOT NULL,
    author     TEXT NOT NULL,
    body       TEXT NOT NULL,
    question   INTEGER NOT NULL DEFAULT 0,
    settles    INTEGER REFERENCES notes (id),
    supersedes INTEGER REFERENCES notes (id),
    artifacts  TEXT NOT NULL,
    created_at TEXT NOT NULL,
    deleted_at TEXT,
    deleted_by TEXT
);
CREATE INDEX IF NOT EXISTS notes_by_subject ON notes (subject, id);
CREATE INDEX IF NOT EXISTS notes_by_settles ON notes (settles);
CREATE INDEX IF NOT EXISTS notes_by_supersedes ON notes (supersedes);
CREATE TABLE IF NOT EXISTS subjects (
    name        TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    created_by  TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    archived_at TEXT,
    archived_by TEXT
);
"""

# Verbatim from `git show 16ef818:src/cairn/store.py`, which is the build every
# machine on the network was running when signing landed — including the hub in
# the container. `messages` has `retracted_at` and no `signature`; `subjects` has
# `described_at` and `described_by`. This is the newest shape here and so the one
# an upgrade will actually meet, which is exactly why it is the easiest to skip.
_BEFORE_SIGNATURES = """
CREATE TABLE IF NOT EXISTS agents (
    name          TEXT PRIMARY KEY,
    machine       TEXT NOT NULL,
    cwd           TEXT NOT NULL,
    capabilities  TEXT NOT NULL,
    session_id    TEXT,
    registered_at TEXT NOT NULL,
    last_seen     TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
    seq            INTEGER PRIMARY KEY AUTOINCREMENT,
    kind           TEXT NOT NULL,
    sender         TEXT NOT NULL,
    recipient      TEXT NOT NULL,
    body           TEXT NOT NULL,
    correlation_id TEXT,
    artifacts      TEXT NOT NULL,
    created_at     TEXT NOT NULL,
    retracted_at   TEXT
);
CREATE TABLE IF NOT EXISTS cursors (
    agent          TEXT PRIMARY KEY,
    last_acked_seq INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS notes (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    subject    TEXT NOT NULL,
    author     TEXT NOT NULL,
    body       TEXT NOT NULL,
    question   INTEGER NOT NULL DEFAULT 0,
    settles    INTEGER REFERENCES notes (id),
    supersedes INTEGER REFERENCES notes (id),
    artifacts  TEXT NOT NULL,
    created_at TEXT NOT NULL,
    deleted_at TEXT,
    deleted_by TEXT
);
CREATE TABLE IF NOT EXISTS subjects (
    name         TEXT PRIMARY KEY,
    description  TEXT NOT NULL,
    created_by   TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    archived_at  TEXT,
    archived_by  TEXT,
    described_at TEXT,
    described_by TEXT
);
CREATE INDEX IF NOT EXISTS messages_by_recipient ON messages (recipient, seq);
CREATE INDEX IF NOT EXISTS messages_by_sender ON messages (sender, seq);
CREATE INDEX IF NOT EXISTS notes_by_subject ON notes (subject, id);
CREATE INDEX IF NOT EXISTS notes_by_settles ON notes (settles);
CREATE INDEX IF NOT EXISTS notes_by_supersedes ON notes (supersedes);
"""

SHIPPED = {
    "before subjects": _BEFORE_SUBJECTS,
    "before supersedes": _BEFORE_SUPERSEDES,
    "before retraction": _BEFORE_RETRACTION,
    "before signatures": _BEFORE_SIGNATURES,
}
"""Every schema shape cairn has put on somebody's disk, oldest first.

Add to this rather than editing it. The whole value of the file is that each entry
is what a build wrote, and an entry that gets quietly refreshed alongside
`store.py` stops being evidence of anything.
"""


def _old_hub(path, schema):
    """Write a database in `schema`'s shape with a little of every kind of content on it.

    Raw SQL, and only over columns that exist in **all** the shapes above, so one
    seeding routine covers every entry in `SHIPPED`. Going through `SqliteStore`
    here instead is the exact mistake this file was written to correct: it would
    upgrade the database before the test got to.
    """
    db = sqlite3.connect(path)
    db.executescript(schema)
    for name in (SCRIBE, PEER):
        db.execute(
            """INSERT INTO agents (name, machine, cwd, capabilities, session_id, registered_at, last_seen)
               VALUES (?, 'bench', '/w/fw', '[]', NULL, '2026-07-01T09:00:00Z', '2026-07-01T09:00:00Z')""",
            (name,),
        )
        db.execute("INSERT INTO cursors (agent, last_acked_seq) VALUES (?, 0)", (name,))
    db.execute(
        """INSERT INTO messages (kind, sender, recipient, body, correlation_id, artifacts, created_at)
           VALUES ('tell', ?, ?, 'jtag adapter is on the shelf, not in the rig', NULL, '[]',
                   '2026-07-01T09:05:00Z')""",
        (SCRIBE, PEER),
    )
    db.execute(
        """INSERT INTO notes (subject, author, body, question, settles, artifacts, created_at)
           VALUES ('rig-a', ?, 'clamp works loose after about an hour of soak', 0, NULL, '[]',
                   '2026-07-01T09:10:00Z')""",
        (SCRIBE,),
    )
    db.commit()
    db.close()


def _indexes(store):
    rows = store._db.execute("SELECT name FROM sqlite_master WHERE type = 'index' AND name NOT LIKE 'sqlite_%'")
    return sorted(r["name"] for r in rows)


def _columns(store, table):
    return sorted(r[1] for r in store._db.execute(f"PRAGMA table_info({table})"))


# -- the crashloop ---------------------------------------------------------------


def test_a_hub_that_missed_three_schema_changes_opens_at_all(tmp_path):
    """The reported failure, reproduced from a hand-written schema rather than a generated one.

    Before the fix this raises `no such column: supersedes` out of the constructor
    — `CREATE TABLE IF NOT EXISTS notes` is a no-op on the six-column `notes`, the
    index over `supersedes` in the same script cannot be built, and `executescript`
    abandons the rest of the script including the `ALTER TABLE` that would have
    added the column. Every restart hits it again, which is what a crashloop is.
    """
    path = tmp_path / "hub.db"
    _old_hub(path, _BEFORE_SUBJECTS)

    store = SqliteStore(path)

    assert store.get_agent(SCRIBE) is not None, "an upgraded hub lost the agent it was holding"
    store.close()


@pytest.mark.parametrize("shape", list(SHIPPED), ids=list(SHIPPED))
def test_every_shape_cairn_has_ever_written_opens(tmp_path, shape):
    """Not just the build before this one.

    The migrations run as an unordered set on every open, so a hub that skipped
    three releases gets all of them in one pass — and the one that actually needed
    it was the oldest shape on the list, not the newest.
    """
    path = tmp_path / "hub.db"
    _old_hub(path, SHIPPED[shape])

    store = SqliteStore(path)

    assert _columns(store, "notes") == _columns(SqliteStore(":memory:"), "notes"), (
        f"a database in the {shape!r} shape opened without being brought up to date"
    )
    assert "retracted_at" in _columns(store, "messages")
    store.close()


def test_an_upgrade_keeps_the_sediment_and_the_mail_that_were_already_there(tmp_path):
    """Opening is not the bar; the reason not to wipe the volume is the content.

    The recovery that was actually performed on the container hub — delete the
    volume, restart — makes the crash go away and takes the notes with it. The
    store is the only copy: a message can at least be resent by whoever sent it,
    but a note is sediment left for somebody who is not here yet.
    """
    path = tmp_path / "hub.db"
    _old_hub(path, _BEFORE_SUBJECTS)

    store = SqliteStore(path)

    entries, total, _ = store.notes("rig-a")
    assert total == 1
    assert entries[0].note.body == "clamp works loose after about an hour of soak"
    assert store.unread(PEER).unread == 1, "the backlog a switched-off peer was owed did not survive the upgrade"
    store.close()


def test_a_subject_that_predates_the_subjects_table_is_backfilled_from_a_real_old_database(tmp_path):
    """The backfill's actual target: a `notes` row whose subject was only ever a string.

    `test_subjects.py` pins the dating and the wording of this against a simulated
    old database. What it cannot show is that the backfill is reached at all on a
    store from before `subjects` existed, because reaching it means surviving the
    three steps in front of it.
    """
    path = tmp_path / "hub.db"
    _old_hub(path, _BEFORE_SUBJECTS)

    store = SqliteStore(path)

    pile = store.get_subject("rig-a")
    assert pile is not None, "a database with notes came back with no subject to write to"
    assert (pile.notes, pile.created_by) == (1, BACKFILLED_AUTHOR)
    store.close()


# -- what the upgrade has to leave behind ----------------------------------------


def test_an_upgraded_hub_takes_the_writes_its_new_columns_are_for(tmp_path):
    """A store that opens and then refuses every new command is the same outage, later.

    Ordering the steps wrongly in the other direction — indexes before tables, or a
    migration silently skipped — passes a constructor and fails here instead, which
    is the poisoned shape this project keeps finding: an exit code that says nothing
    happened over a hub that is broken.
    """
    path = tmp_path / "hub.db"
    _old_hub(path, _BEFORE_SUBJECTS)
    store = SqliteStore(path)
    store.register(Agent(name=SCRIBE, machine="bench", cwd="/w/fw"))

    correction = store.write_note(SCRIBE, "it is the mount, not the clamp", supersedes=1)
    doomed = store.write_note(SCRIBE, "left the adapter serial in here", subject="rig-a")
    store.delete_note(doomed.id, SCRIBE, "had a serial number in it")
    sent = store.append("tell", SCRIBE, PEER, "ignore that last one")
    withdrawal = store.retract(sent.seq, SCRIBE)
    signed = store.append("tell", SCRIBE, PEER, "and this one is signed", signature="deadbeef")

    described, replaced = store.describe_subject("rig-a", "thermal chamber A, and its fixture", SCRIBE)

    assert correction.supersedes == 1, "`supersedes` did not survive the round trip"
    assert store.get_note(doomed.id).deleted, "`deleted_at` did not survive the round trip"
    assert withdrawal.withheld == 1, "`retracted_at` did not survive the round trip"
    # Read back through `sent` rather than trusting what `append` returned: the
    # return value is built in Python and would carry the signature even if the
    # INSERT had dropped it on the floor, which is the whole failure an upgraded
    # column is capable of.
    stored, _ = store.sent(SCRIBE)
    assert next(m.signature for m in stored if m.seq == signed.seq) == "deadbeef", (
        "`signature` did not survive the round trip"
    )
    # `described_at`/`described_by` alter `subjects`, which the oldest shape does not
    # have at all — the ALTER is suppressed there and `_TABLES` supplies the columns
    # instead, while a mid-age database gets them from the ALTER. Both routes have to
    # arrive at a writable column, and only one of them is exercised by a fresh open.
    assert described.described_by == SCRIBE, "`described_by` did not survive the round trip"
    assert replaced, "the backfilled description was not returned as the text replaced"
    store.close()


def test_an_upgraded_hub_ends_up_indexed_like_a_fresh_one(tmp_path):
    """Moving the index script late must not turn into not running it.

    The cheapest wrong fix for the crashloop is to drop `notes_by_supersedes`, and
    it would be green everywhere except a slow hub two years from now.
    """
    path = tmp_path / "hub.db"
    _old_hub(path, _BEFORE_SUBJECTS)

    upgraded = SqliteStore(path)

    assert _indexes(upgraded) == _indexes(SqliteStore(":memory:"))
    upgraded.close()


def test_opening_an_already_upgraded_hub_is_a_no_op(tmp_path):
    """Every restart re-runs all four steps, so the second one has to be as quiet as the first."""
    path = tmp_path / "hub.db"
    _old_hub(path, _BEFORE_SUBJECTS)
    once = SqliteStore(path)
    before = (_indexes(once), _columns(once, "notes"), json.dumps([s.subject for s in once.subjects()]))
    once.close()

    twice = SqliteStore(path)

    assert (_indexes(twice), _columns(twice, "notes"), json.dumps([s.subject for s in twice.subjects()])) == before
    twice.close()


# -- the shape of the fix, pinned ------------------------------------------------


def test_the_table_script_holds_no_index_and_the_index_script_holds_no_table(tmp_path):
    """One `CREATE INDEX` in the wrong literal rebuilds the crashloop, and only against old data.

    This is the assertion the other tests in this file cannot make cheaply: they
    catch a *column* that is missing today, while this catches the next index over
    the next migrated column, before anybody has an old database to prove it with.
    Merging the two literals back together is the specific regression.
    """
    assert "CREATE INDEX" not in _TABLES.upper(), (
        "an index in the table script runs before the migration its column needs; put it in `_INDEXES`"
    )
    assert "CREATE TABLE" not in _INDEXES.upper(), (
        "a table in the index script runs after the migrations that alter it; put it in `_TABLES`"
    )
